
home:
  hero:
    name: Hexo Theme Sea
    intro: Hexo Theme Sea is a simple and elegant Hexo blog theme with built-in support for internationalization, light and dark modes, customizable themes, and seamless integration of comments (Waline, Giscus) and search (Algolia).
    avatar: logo.svg
  posts: recommend

articles:
  path: 'posts'
  per_page: 10
  order_by: -date

menu:
  - name: Posts
    url: /posts/
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: Archives
    url: /archives/

socialLink:
  - name: Github
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Facebook
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Telegram
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Instagram
    link: https://github.com/hai-zou/hexo-theme-sea

friends:
  - name: 旧梦
    avatar: //imgs.izou.top/images/userInfo/avatar.jpg
    link: //blog.izou.top
    desc: 冰冻三尺非一日之寒，滴水穿石非一日之功

works:
  - name: Hexo Theme Sea
    desc: Blog Theme
    tags:
      - HTML
      - CSS
      - JavaScript
    link: //www.izou.top
    cover: //imgs.izou.top/images/blog/2025/0118/1407.webp

footer:
  builtUpTime: 2024-05-28

favicon: /logo.svg

comment:
  enable: true
  type: giscus

search:
  enable: true
  type: pagefind

giscus:
  repo: hai-zou/hexo-theme-sea
  repoid: R_kgDOLD6S2g
  category: General
  categoryid: DIC_kwDOLD6S2s4CgP0r
  mapping: pathname
  strict: "0"
  reactionsenabled: "1"
  emitmetadata: "0"
  inputposition: bottom
  loading: lazy