
home:
  hero:
    name: Hexo Theme Sea
    intro: Hexo Theme Sea is a simple and elegant Hexo blog theme with built-in support for internationalization, light and dark modes, customizable themes, and seamless integration of comments (Waline, Giscus) and search (Algolia).
    avatar: logo.svg
  posts: recent

articles:
  path: ''
  per_page: 10
  order_by: -date

menu:
  - name: Posts
    url: /articles/
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: Archives
    url: /archives/
  - name: Friends
    url: /friends/

socialLink:
  - name: Github
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Facebook
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Telegram
    link: https://github.com/hai-zou/hexo-theme-sea
  - name: Instagram
    link: https://github.com/hai-zou/hexo-theme-sea

friends:
  - name: 旧梦
    avatar: //imgs.izou.top/images/userInfo/avatar.jpg
    link: //blog.izou.top
    desc: 冰冻三尺非一日之寒，滴水穿石非一日之功

footer:
  builtUpTime: 2024-05-28

comment:
  enable: true
  type: giscus

giscus:
  repo: hai-zou/hexo-theme-sea
  repoid: R_kgDOLD6S2g
  category: General
  categoryid: DIC_kwDOLD6S2s4CgP0r
  mapping: pathname
  strict: "0"
  reactionsenabled: "1"
  emitmetadata: "0"
  inputposition: bottom
  loading: lazy