# 首页配置
home:
  hero:
    name: # 名称
    intro: # 个人简介
    avatar: # 头像
  posts: recent # recent: 最新文章 | recommend: 推荐文章

# 所有文章
articles:
  path: 'articles' # 路由
  per_page: 10 # 分页数
  order_by: -date # 文章排序

# 菜单栏
menu:
  # - name: 归档
  #   url: /archives/
  # - name: 友链
  #   url: /friends/
  # - name: 留言
  #   url: /messages/
  # - name: 关于
  #   url: /about/

comment:
  enable: false
  type: # waline | giscus

# Waline https://waline.js.org/
waline:
  serverURL:
  options:

# Giscus https://giscus.app/zh-CN
giscus:
  repo:
  repoid:
  category:
  categoryid:
  mapping:
  term:
  reactionsenabled:
  emitmetadata:
  inputposition:
  loading:

search:
  enable: false
  type: # algolia | pagefind

# Docsearch https://docsearch.algolia.com/apply/
algolia:
  appId: 
  apiKey: 
  indexName: 

# 友链模块
friends:
  # - name: xxx's blog
  #   avatar: https://xx.png
  #   link: https://blog.xxx.com
  #   desc: xxx

footer:
  builtUpTime: # 2020-05-20 13:14:00

# 社交链接
socialLink:
  # - name: Email
  #   link: mailto:xx@xx.com
  # - name: RSS
  #   link: rss link

# 主题色
primaryColor: '#10b981'

# 目录
tableOfContents:
  enable: true